"""replies update updated_at model

Revision ID: 5be43b3f6f7c
Revises: 809fbfd64ed9
Create Date: 2025-06-29 22:05:07.688992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be43b3f6f7c'
down_revision: Union[str, None] = '809fbfd64ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'updated_at')
    # ### end Alembic commands ###
