"""Progress add container progress table again 

Revision ID: 68e4b6e380fd
Revises: 86bdd29478ea
Create Date: 2025-07-07 22:42:16.226661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e4b6e380fd'
down_revision: Union[str, None] = '86bdd29478ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_detail_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BKNo', sa.String(length=100), nullable=True),
    sa.Column('LINE', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('VESSEL', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('DOC', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('PARTNER', sa.String(length=20), nullable=True),
    sa.Column('ETA', sa.DateTime(), nullable=True),
    sa.Column('ETD', sa.DateTime(), nullable=True),
    sa.Column('PAYMENT', sa.String(length=20), nullable=True),
    sa.Column('ATD', sa.DateTime(), nullable=True),
    sa.Column('SHIPPER', sa.String(length=50), nullable=True),
    sa.Column('DESTINATION', sa.String(length=50), nullable=True),
    sa.Column('BUY', sa.Integer(), nullable=True),
    sa.Column('SELL', sa.Integer(), nullable=True),
    sa.Column('SHORING', sa.Integer(), nullable=True),
    sa.Column('TRUCKING', sa.Integer(), nullable=True),
    sa.Column('THC', sa.Integer(), nullable=True),
    sa.Column('WFG', sa.Integer(), nullable=True),
    sa.Column('SECURITY', sa.Integer(), nullable=True),
    sa.Column('CARRIER', sa.Integer(), nullable=True),
    sa.Column('PARTNER_FEE', sa.Integer(), nullable=True),
    sa.Column('OTHER', sa.Integer(), nullable=True),
    sa.Column('RATE', sa.Float(), nullable=True),
    sa.Column('PROFIT_USD', sa.Float(), nullable=True),
    sa.Column('PROFIT_KRW', sa.Float(), nullable=True),
    sa.Column('SALESMAN', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progress_id'], ['progress.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_detail_container_id'), 'progress_detail_container', ['id'], unique=False)
    op.create_table('progress_detail_container_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MODEL', sa.String(length=30), nullable=True),
    sa.Column('CHASSISNo', sa.String(length=30), nullable=True),
    sa.Column('WEIGHT', sa.Integer(), nullable=True),
    sa.Column('EL', sa.Boolean(), nullable=True),
    sa.Column('HBL', sa.String(length=50), nullable=True),
    sa.Column('progress_detail_container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progress_detail_container_id'], ['progress_detail_container.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_detail_container_detail_id'), 'progress_detail_container_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_detail_container_detail_id'), table_name='progress_detail_container_detail')
    op.drop_table('progress_detail_container_detail')
    op.drop_index(op.f('ix_progress_detail_container_id'), table_name='progress_detail_container')
    op.drop_table('progress_detail_container')
    # ### end Alembic commands ###
