"""Add Column progress again

Revision ID: a0a19b8b4efd
Revises: e5b8bf428210
Create Date: 2025-07-06 10:34:35.222193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a19b8b4efd'
down_revision: Union[str, None] = 'e5b8bf428210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_detail_roro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BKNo', sa.String(length=100), nullable=True),
    sa.Column('LINE', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('VESSEL', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('DOC', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('PARTNER', sa.String(length=20), nullable=True),
    sa.Column('ETA', sa.DateTime(), nullable=True),
    sa.Column('ETD', sa.DateTime(), nullable=True),
    sa.Column('PAYMENT', sa.String(length=20), nullable=True),
    sa.Column('ATD', sa.DateTime(), nullable=True),
    sa.Column('SHIPPER', sa.String(length=50), nullable=True),
    sa.Column('DESTINATION', sa.String(length=50), nullable=True),
    sa.Column('SMALL', sa.Integer(), nullable=True),
    sa.Column('BUY_SMALL', sa.Integer(), nullable=True),
    sa.Column('S_SUV', sa.Integer(), nullable=True),
    sa.Column('BUY_S_SUV', sa.Integer(), nullable=True),
    sa.Column('SUV', sa.Integer(), nullable=True),
    sa.Column('BUY_SUV', sa.Integer(), nullable=True),
    sa.Column('RV_CARGO', sa.Integer(), nullable=True),
    sa.Column('BUY_RV_CARGO', sa.Integer(), nullable=True),
    sa.Column('SPECIAL', sa.Integer(), nullable=True),
    sa.Column('BUY_SPECIAL', sa.Integer(), nullable=True),
    sa.Column('CBM', sa.Integer(), nullable=True),
    sa.Column('BUY_CBM', sa.Integer(), nullable=True),
    sa.Column('SELL', sa.Integer(), nullable=True),
    sa.Column('HC', sa.Integer(), nullable=True),
    sa.Column('WFG', sa.Integer(), nullable=True),
    sa.Column('SECURITY', sa.Integer(), nullable=True),
    sa.Column('CARRIER', sa.Integer(), nullable=True),
    sa.Column('PARTNER_FEE', sa.Integer(), nullable=True),
    sa.Column('OTHER', sa.Integer(), nullable=True),
    sa.Column('RATE', sa.Integer(), nullable=True),
    sa.Column('PROFIT_USD', sa.Integer(), nullable=True),
    sa.Column('PROFIT_KRW', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progress_id'], ['progress.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_detail_roro_id'), 'progress_detail_roro', ['id'], unique=False)
    op.create_table('progress_detail_roro_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MODEL', sa.String(length=30), nullable=True),
    sa.Column('CHASSISNo', sa.String(length=30), nullable=True),
    sa.Column('EL', sa.Boolean(), nullable=True),
    sa.Column('HBL', sa.String(length=50), nullable=True),
    sa.Column('progress_detail_roro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['progress_detail_roro_id'], ['progress_detail_roro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_detail_roro_detail_id'), 'progress_detail_roro_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_detail_roro_detail_id'), table_name='progress_detail_roro_detail')
    op.drop_table('progress_detail_roro_detail')
    op.drop_index(op.f('ix_progress_detail_roro_id'), table_name='progress_detail_roro')
    op.drop_table('progress_detail_roro')
    # ### end Alembic commands ###
