"""Progress add some column

Revision ID: f476c9029017
Revises: 1391622df628
Create Date: 2025-07-07 22:06:10.848600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f476c9029017'
down_revision: Union[str, None] = '1391622df628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_detail_roro', sa.Column('SALESMAN', sa.String(length=20), nullable=True))
    op.add_column('progress_detail_roro_detail', sa.Column('WEIGHT', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress_detail_roro_detail', 'WEIGHT')
    op.drop_column('progress_detail_roro', 'SALESMAN')
    # ### end Alembic commands ###
